<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My records';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 
 <p>
 
 <h4><?php echo $this->escapeHtml('search by user name'); ?></h4>
 <?php
 $form->setAttribute('action', $this->url('index', array('action' => 'index')));
 $form->setAttribute('method', 'get');
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('userName'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>
 </p>
 
 
 <p>
     <a href="<?php echo $this->url('index', array('action'=>'add'));?>">Add new record</a>
 </p>

 <table class="table">
 <tr>
     <th>User Name</th>
	 <th>Email</th>
     <th>First Name</th>	 
     <th>Last Name</th>	 
     <th>Profile Type</th>	
     <th>Enabled</th>	 
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 
 <?php #echo "<pre>", print_r($album, 1), "</pre>";?>

 <tr>
     <td><?php echo $this->escapeHtml($album->userName);?></td>
	 <td><?php echo $this->escapeHtml($album->email);?></td>
     <td><?php echo $this->escapeHtml($album->firstName);?></td>	 
     <td><?php echo $this->escapeHtml($album->lastName);?></td>	 
     <td><?php echo $this->escapeHtml($album->profileType);?></td>
     <td><?php echo $this->escapeHtml($album->enabled);?></td>

     <td>
         <a href="<?php echo $this->url('index',
             array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
         <a href="<?php echo $this->url('index',
             array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>